### ISSUE TITLE
request to complete implimentation of Polyline.offset()

### ISSUE THREAD

**Issue by KEERTHANAUDAY** [compas-dev/compas#1299]
request to complete implementation of polyline.offset() method.

current error on running polyline.offset() 
```
Traceback (most recent call last):
  File "file:///C:/Users/Uday/uday_dev/sbp_academy_24/scripts/A_00_inputs_canopy_comp.py", line 15, in <module>
  File "C:\Users\Uday\.rhinocode\py39-rh8\site-envs\default-KA6C24DI\compas\geometry\curves\curve.py", line 605, in offset
    raise NotImplementedError
NotImplementedError: 

```

**Comment by tomvanmele** [comment]
can you provide a bit more context? a code snippet that triggers this error would be helpful...
