### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'neighbors'

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas#326]
**To Reproduce**
```
>>> import compas
>>> from compas.datastructures import Mesh
>>> mesh = Mesh.from_obj(compas.get('faces.obj'))
>>> mesh.vertex_neighborhood_centroid(0)
```

**Expected behavior**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lichen7/WORK/compas/src/compas/datastructures/mesh/_mesh.py", line 2579, in vertex_neighborhood_centroid
    return centroid_points([self.vertex_coordinates(nbr) for nbr in self.neighbors(key)])
AttributeError: 'Mesh' object has no attribute 'neighbors'
>>> 

```

 - OS: OS X
 - Python version 3.7
 - Python package manager conda

**Comment by tomvanmele** [comment]
should be `self.vertex_neighbors` i guess

**Comment by Licini** [comment]
right, that make senses, gonna fix it in next pull
