### ISSUE TITLE
Translation method TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by nizartaha** [compas-dev/compas#573]
**Describe the bug**
error in tranlsation method `compas.geometry.Translation
` when using a latest compas version  
`Tx = Translation([3, 0, 0])`

```
compas version:  0.16.1
Traceback (most recent call last):
  File "c:/Users/nizart/Documents/Projects/robotic_aerocrete/src/robotic_aerocrete/spray_geometry/spray_frames.py", line 153, in <module>
    Tx = Translation([3, 0, 0])
  File "C:\ProgramData\Anaconda3\envs\igl\lib\site-packages\compas\geometry\_transformations\translation.py", line 67, in __init__
    _, _, _, translation, _ = decompose_matrix(matrix)
  File "C:\ProgramData\Anaconda3\envs\igl\lib\site-packages\compas\geometry\_transformations\matrices.py", line 273, in decompose_matrix
    detM = matrix_determinant(M)  # raises ValueError if matrix is not squared
  File "C:\ProgramData\Anaconda3\envs\igl\lib\site-packages\compas\geometry\_transformations\matrices.py", line 140, in matrix_determinant
    if not is_matrix_square(M):
  File "C:\ProgramData\Anaconda3\envs\igl\lib\site-packages\compas\geometry\_transformations\matrices.py", line 101, in is_matrix_square
    if len(row) != number_of_rows:
TypeError: object of type 'int' has no len()
```

**To Reproduce**
```
import compas

from compas.geometry import Translation
Tx = Translation([3, 0, 0])
print (Tx)
```

**Expected behavior**
```
compas version:  0.15.6
[[    1.0000,    0.0000,    0.0000,    3.0000],
 [    0.0000,    1.0000,    0.0000,    0.0000],
 [    0.0000,    0.0000,    1.0000,    0.0000],
 [    0.0000,    0.0000,    0.0000,    1.0000]]

```

**Comment by tomvanmele** [comment]
the method you are looking for is `Translation.from_vector([3, 0, 0])`

**Comment by nizartaha** [comment]
Thanks
