### ISSUE TITLE
Install COMPAS V16.6 packages in Rhino

### ISSUE THREAD

**Issue by Gaspard-Bourgeois** [compas-dev/compas#624]
**Describe the bug**
`(COMPAS) C:\Users\gbourgeois\Documents\COMPAS\workshop_tokyo_2020>python -m compas_rhino.install -p compas compas_rhino compas_ghpython compas_fab
Installing COMPAS packages to Rhino 6.0 scripts folder:
Location scripts folder: C:\Users\gbourgeois\AppData\Roaming\McNeel\Rhinoceros\6.0\scripts

Traceback (most recent call last):
  File "C:\Users\gbourgeois\Anaconda3\envs\COMPAS\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gbourgeois\Anaconda3\envs\COMPAS\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\gbourgeois\Anaconda3\envs\COMPAS\lib\site-packages\compas_rhino\install.py", line 198, in <module>
    install(version=args.version, packages=args.packages)
  File "C:\Users\gbourgeois\Anaconda3\envs\COMPAS\lib\site-packages\compas_rhino\install.py", line 61, in install
    package_path = compas_rhino._get_package_path(importlib.import_module(package))
  File "C:\Users\gbourgeois\Anaconda3\envs\COMPAS\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'compas_fab'`

**To Reproduce**
1. `conda create -n COMPAS COMPAS`
2. `conda activate COMPAS`
3. `python -m compas_rhino.install -p compas compas_rhino compas_ghpython compas_fab`

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Python 3.8.5

**Comment by Gaspard-Bourgeois** [comment]
I didn't figure out that Compas Fab wasn't install with Compas by default.
Probem solved with:
`conda install -c conda-forge compas_fab`
