### ISSUE TITLE
PluginNotInstalledError, NurbsCurve and NurbsSurface frome compas core 

### ISSUE THREAD

**Issue by ghost** [compas-dev/compas#953]
Hey,
User of orbingol's nurbs python, I'm more attracted to your future developpements with OCC thant ACIS :D Cheers !

But :

**Describe the bug**
Using the compas core geometry, a plugin is required to use NurbsCurve and NurbsSurface, the given url is inactive and the slug mention "factories", I've got no clue of what it might be :  https:/plugins.compas.dev/factories/new_nurbscurve_from_points

Obviously, a plugin is needed, but which one ? I've found [compas_nurbs ](https://gramaziokohler.github.io/compas_nurbs/latest/)in gk's github but that seems to be something entirely different.

**To Reproduce**
In vscode

```python
import numpy as np
from compas.geometry import Point, NurbsCurve, NurbsSurface

points = np.array([
    [0.0,  0.0, 0.0], 
    [10.0, 0.0, 0.0],
    [0.0, 10.0, 0.0], 
    [10.0,10.0, 0.0], 
    ])

nc2 = NurbsCurve.from_points( [Point(*points[2]), Point(*points[3])], degree=2)
```

```
Traceback (most recent call last):
  File "c:/_Archi/Etudes/21ASTRA_/4a_Segmentation-masonry/a1-piclouToTexture/a1-tests.py", line 23, in <module>
    nc1 = NurbsCurve.from_points( [p1,p2], degree=2)
  File "C:\Users\antgr\anaconda3\envs\geocc37\lib\site-packages\compas\geometry\curves\nurbs.py", line 188, in from_points
    return new_nurbscurve_from_points(points, degree=degree)
  File "C:\Users\antgr\anaconda3\envs\geocc37\lib\site-packages\compas\plugins.py", line 289, in wrapper
    plugin_impl = _select_plugin(extension_point_url)
  File "C:\Users\antgr\anaconda3\envs\geocc37\lib\site-packages\compas\plugins.py", line 464, in select_plugin
    raise PluginNotInstalledError('Plugin not found for extension point URL: {}'.format(extension_point_url))
compas.plugins.PluginNotInstalledError: Plugin not found for extension point URL: https:/plugins.compas.dev/factories/new_nurbscurve_from_points
```

**Expected behavior**
Build a NurbsCurve from two points.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Python version : 3.7
 - Python package manager conda

**Additional context**

Packages in my conda env :
```
# packages in environment at C:\xxx\anaconda3\envs\geocc37:
#
# Name                    Version                   Build  Channel
argcomplete               1.12.3             pyhd8ed1ab_2    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               21.1.0           py37hcc03f2d_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cffi                      1.15.0           py37hd8e9650_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
compas                    1.13.2           py37h03978a9_0    conda-forge
compas_view2              0.4.4            py37h03978a9_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
curl                      7.80.0               h789b8ee_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.23          py37hf2a7229_1    conda-forge
debugpy                   1.5.1            py37hf2a7229_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
double-conversion         3.1.6                h0e60522_0    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
ezdxf                     0.17             py37h8c56517_1    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freeglut                  3.2.1                h0e60522_2    conda-forge
freeimage                 3.18.0               hfcb8cd7_7    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freetype-py               2.2.0              pyh9f0ad1d_0    conda-forge
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
ilmbase                   2.5.5                h12d4b20_0    conda-forge
imageio                   2.13.3             pyh239f2a4_0    conda-forge
importlib-metadata        4.8.2            py37h03978a9_0    conda-forge
importlib_metadata        4.8.2                hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
ipydatawidgets            4.2.0              pyhd3deb0d_0    conda-forge
ipykernel                 6.6.0            py37h4038f58_0    conda-forge
ipython                   7.30.1           py37h03978a9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py37h03978a9_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsoncpp                   1.9.4                h2d74725_3    conda-forge
jsonschema                4.2.1              pyhd8ed1ab_1    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py37h03978a9_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kiwisolver                1.3.2            py37h8c56517_1    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
laspy                     2.0.3              pyh8a188c0_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.80.0               h789b8ee_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.8.0           nompi_hf689e7d_103    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libraw                    0.20.2               hee1bdec_1    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtheora                 1.1.1             h8d14728_1005    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libxslt                   1.1.33               h65864e5_3    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.36.0           py37habb0c8c_0    conda-forge
loguru                    0.5.3            py37h03978a9_3    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1            py37hcc03f2d_1    conda-forge
matplotlib-base           3.0.3            py37h3e3dc42_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py37hcc03f2d_1005    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py37h03978a9_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
networkx                  2.5                        py_0    conda-forge
notebook                  6.4.6              pyha770c72_0    conda-forge
numba                     0.53.1           py37h9690626_1    conda-forge
numpy                     1.21.4           py37h940b05c_0    conda-forge
occt                      7.5.3                h60997fb_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
open3d                    0.11.2                   py37_0    open3d-admin
openexr                   2.5.5                hab3b255_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandoc                    2.16.2               h8ffe710_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py37hd7d9ad0_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
planarity                 3.0.0.5           hfa6e2cd_1002    conda-forge
proj                      7.2.0                h1cfcee9_2    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
pugixml                   1.11.4               h0e60522_0    conda-forge
pycollada                 0.7.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pymeshlab                 2021.10                  pypi_0    pypi
pyopengl                  3.1.5                      py_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyransac3d                0.6.0                    pypi_0    pypi
pyrsistent                0.18.0           py37hcc03f2d_0    conda-forge
pyside2                   5.13.2           py37h760f651_4    conda-forge
python                    3.7.12          h7840368_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-planarity          0.4.1            py37hcc03f2d_6    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pythonocc-core            7.5.1            py37h8c6f293_0    conda-forge
pythreejs                 2.3.0              pyhd8ed1ab_0    conda-forge
pywin32                   302              py37hcc03f2d_2    conda-forge
pywinpty                  1.1.6            py37h7f67f24_0    conda-forge
pyyaml                    6.0              py37hcc03f2d_3    conda-forge
pyzmq                     22.3.0           py37hcce574b_1    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
rapidjson                 1.1.0             ha925a31_1002    conda-forge
schema                    0.7.5              pyhd8ed1ab_0    conda-forge
scipy                     1.7.3            py37hb6553fb_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.4.0           py37h03978a9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
sympy                     1.9              py37h03978a9_1    conda-forge
tbb                       2020.2               h2d74725_4    conda-forge
tbb-devel                 2020.2               h2d74725_4    conda-forge
terminado                 0.12.1           py37h03978a9_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
tornado                   6.1              py37hcc03f2d_2    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
utfcpp                    3.2.1                h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
vtk                       9.0.1           no_osmesa_py37h96b1751_107    conda-forge
watchdog                  2.1.6            py37h03978a9_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.2            py37h03978a9_1    conda-forge
win32_setctime            1.0.4              pyhd8ed1ab_0    conda-forge
winpty                    0.4.3                         4    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```

Best Regards,
Antoine

**Comment by romanarust** [comment]
Hi Antoine,

you need [compas_occ](https://github.com/compas-dev/compas_occ).
compas_nurbs will not be developed any further, as is replaced by the interface to occ.

**Comment by tomvanmele** [comment]
hi, maybe a small thing to add to that is that the docs of `compas_occ` are a bit outdated. it is available on `conda-forge` now so you can just do

```bash
conda install -c conda-forge compas compas_occ --yes
```

**Comment by ghost** [comment]
Hey,

Thanks for the quick reply, installing compas_occ was the next step, I didn't understood that is was needed right now


After `conda install -c conda-forge compas compas_occ --yes` I had a TypeError on the Curve from lines example
```
Traceback (most recent call last):
  File "c:/_Archi/Etudes/21ASTRA_/4a_Segmentation-masonry/a1-piclouToTexture/a0-tests2.py", line 8, in <module>
    curve = NurbsCurve.from_line(line)
  File "C:\Users\antgr\anaconda3\envs\geocc37\lib\site-packages\compas_occ\geometry\curves\nurbs.py", line 386, in from_line
    degree=1
  File "C:\Users\antgr\anaconda3\envs\geocc37\lib\site-packages\compas_occ\geometry\curves\nurbs.py", line 216, in from_parameters
    curve = cls()
  File "C:\Users\antgr\anaconda3\envs\geocc37\lib\site-packages\compas\geometry\curves\nurbs.py", line 96, in __new__
    return new_nurbscurve(*args, **kwargs)
  File "C:\Users\antgr\anaconda3\envs\geocc37\lib\site-packages\compas\plugins.py", line 292, in wrapper
    return plugin_impl.method(*args, **kwargs)
TypeError: new_nurbscurve() missing 1 required positional argument: 'cls'
```

So I installed the last pack : `pip install git+https://github.com/compas-dev/compas_occ.git`

And now, everything is fine
Cheers !

Antoine

ps : I've just seen your forum, https://forum.compas-framework.org/ which will be more suited for the next times :)
